//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace ProjectNeon
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Customer>();
                db.CreateTable<Invoice>();
                db.CreateTable<Item>();
            }
        }
    }
    public partial class Customer
    {
        [PrimaryKey, AutoIncrement]
        public Int64 CustomerID { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String FirstName { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String LastName { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String AddressLine1 { get; set; }
        
        [MaxLength(50)]
        public String AddressLine2 { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String City { get; set; }
        
        [MaxLength(2)]
        [NotNull]
        public String State { get; set; }
        
        [MaxLength(5)]
        [NotNull]
        public String Zip { get; set; }
        
    }
    
    public partial class Invoice
    {
        [PrimaryKey]
        [MaxLength(50)]
        public String InvoiceID { get; set; }
        
        [NotNull]
        public Int32 CustomerID { get; set; }
        
        [NotNull]
        public Boolean TaxExempt { get; set; }
        
        [NotNull]
        public Double Total { get; set; }
        
        [NotNull]
        public DateTime DateIssued { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String PaymentMethod { get; set; }
        
        [MaxLength(50)]
        public String CheckNum { get; set; }
        
    }
    
    public partial class Item
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ItemID { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String InvoiceID { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String ItemCode { get; set; }
        
        [NotNull]
        public Byte Quantity { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String Description { get; set; }
        
        [NotNull]
        public Double PriceEach { get; set; }
        
    }
    
}
